export const POSTS = {
  LOAD: "LOAD_POSTS",
  LOAD_SUCCESS: "LOAD_POSTS_SUCCESS",
  LOAD_FAILURE: "LOAD_POSTS_FAILURE",
  ADD_POST: "ADD_POST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_SUCCESS",
  DELETE_POST: "DELETE_POST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE"
};
