export const POSTS = {
  LOAD: "LOAD_POSTS",
  ADD: "ADD_POST",
  DELETE: "DELETE_POST",
  UPDATE: "UPDATE_POST",
  POST_SUCCESS: "POST_SUCCESS",
  POST_SUCCESS_MESSAGE: "POST_SUCCESS_MESSAGE",
  POST_CHANGED: "POST_CHANGED",
  POST_FAILURE: "POST_FAILURE"
};
