export const POSTS = {
  LOAD: "LOAD_POSTS",
  LOAD_SUCCESS: "LOAD_POSTS_SUCCESS",
  LOAD_FAILURE: "LOAD_POSTS_FAILURE",
  ADD_POST: "ADD_POST",
  DELETE_POST: "DELETE_POST",
  UPDATE_POST: "UPDATE_POST"
};
